### ISSUE TITLE
[Login] - Não foi informado usuário e senha para acesso do aplicativo. 

### ISSUE THREAD

**Issue by mvalbuquerque** [MatheusMartinsR/cp#1]
Prezado favor informar o usuário e senha utilizado em seu aplicativo. 

Aguardo. 

![Login](https://github.com/MatheusMartinsR/cp/assets/14190112/46ea4252-f9d8-41aa-9220-b42019564122)

**Comment by MatheusMartinsR** [comment]
Boa tarde, qualquer um da API que foi passada

Em dom., 19 de mai. de 2024 às 12:54, @mvalbuquerque <
***@***.***> escreveu:

**Comment by mvalbuquerque** [comment]
Ok. Obrigado.
